insert into project (ProjectID, ProjectName, deadline) values (1, 'Qsymia', to_date('23/03/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (2, 'Ondansetron', to_date('02/01/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (3, 'CD DiorSnow White Reveal UV Shield Foundation 012-Porcelain', to_date('24/08/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (4, 'CVS Pharmacy Oil Free Faces SPF 30', to_date('02/11/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (5, 'Cyclopentolate Hydrochloride', to_date('23/04/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (6, 'Venlafaxine', to_date('27/08/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (7, 'Gabapentin', to_date('06/10/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (8, 'Optimal Diet Plan', to_date('27/01/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (9, 'LifeStyles EPIC Male Genital Desensitizer', to_date('06/09/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (10, 'Calc. carb. Cortex Quercus Special Order', to_date('24/03/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (11, 'Cold and Allergy Relief', to_date('18/04/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (12, 'MUSCLE', to_date('18/09/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (13, 'Divigel', to_date('20/05/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (14, 'Soft Care Hand Sanitizer', to_date('14/03/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (15, 'Treatment Set TS343825', to_date('07/07/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (16, 'Saline Laxative', to_date('27/07/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (17, 'Necon 10/11', to_date('07/01/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (18, 'Double T', to_date('24/04/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (19, 'Captopril', to_date('19/07/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (20, 'Glyburide', to_date('20/09/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (21, 'Verapamil Hydrochloride', to_date('16/12/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (22, 'Healthy Accents Pain Relief PM', to_date('30/03/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (23, 'Escitalopram', to_date('06/04/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (24, 'Lamotrigine', to_date('17/11/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (25, 'Miconazole Nitrate', to_date('04/04/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (26, 'Pollens - Trees, Cedar, Red Juniperus virginiana', to_date('17/12/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (27, 'Pain Relief', to_date('02/06/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (28, 'Blockout Foot Wipes', to_date('07/05/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (29, 'sildenafil', to_date('02/01/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (30, 'Metformin Hydrochloride', to_date('04/11/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (31, 'DICLEGIS', to_date('06/05/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (32, 'TRAMADOL HYDROCHLORIDE', to_date('20/06/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (33, 'Alprazolam', to_date('22/01/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (34, 'Sleep RELIEF', to_date('23/06/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (35, 'Morphine Sulfate', to_date('22/05/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (36, 'Phentermine Hydrochloride', to_date('14/08/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (37, 'White Oak', to_date('02/10/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (38, 'Smart Sense Allergy Relief', to_date('25/01/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (39, 'Ibuprofen', to_date('13/05/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (40, 'Plaster', to_date('08/07/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (41, 'Treatment Set TS347226', to_date('01/09/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (42, 'ShopRite Gas Relief', to_date('11/08/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (43, 'Crotalus terrificus 30 Special Order', to_date('25/06/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (44, 'Calamine', to_date('09/11/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (45, 'Synercid', to_date('22/07/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (46, 'VestalCare Spot Free Psoriasis', to_date('07/12/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (47, 'Anticavity Fluoride Rinse', to_date('03/03/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (48, 'Ampicillin', to_date('14/06/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (49, 'Treatment Set TS349186', to_date('12/06/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (50, 'EQUALINE', to_date('27/11/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (51, 'SODIUM SULFACETAMIDE', to_date('12/11/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (52, 'NEOMYCIN AND POLYMYXIN B SULFATES AND GRAMICIDIN', to_date('03/02/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (53, 'Amoxicillin and Clavulanate Potassium', to_date('17/06/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (54, 'GOAT MILK AND LAVENDER SUN', to_date('29/12/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (55, 'Topiramate', to_date('06/02/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (56, 'LATISSE', to_date('26/05/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (57, 'Hydrocodone Polistirex and Chlorpheniramine Polistirex Pennkinetic', to_date('11/04/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (58, 'Propoxyphene Hydrochloride', to_date('22/02/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (59, 'Piroxicam', to_date('27/11/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (60, 'Hydrocodone Bitartrate and Acetaminophen', to_date('19/12/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (61, 'Platinum Cichorium', to_date('30/12/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (62, 'Letrozole', to_date('23/04/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (63, 'Levothyroxine sodium', to_date('22/01/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (64, 'CYCLOBENZAPRINE HYDROCHLORIDE', to_date('08/12/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (65, 'Doxycycline Hyclate', to_date('15/10/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (66, 'Methylphenidate Hydrochloride', to_date('18/10/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (67, 'Tamsulosin Hydrochloride', to_date('02/05/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (68, 'AMBROSIA PSILOSTACHYA POLLEN', to_date('29/01/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (69, 'Lenscale Quailbrush', to_date('04/12/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (70, 'Lidocaine Hydrochloride', to_date('29/08/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (71, 'clindamycin phosphate', to_date('05/11/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (72, 'MDSolarSciences', to_date('15/06/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (73, 'RUE21 Sugar Cookie Antibacterial Hand Sanitizer', to_date('28/12/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (74, 'SIMPLY RIGHT', to_date('29/07/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (75, 'ENALAPRIL MALEATE', to_date('01/12/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (76, 'MS Contin', to_date('18/10/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (77, 'oxaliplatin', to_date('25/06/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (78, 'Dr. Dream Advanced Facial Treatment Serum', to_date('28/06/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (79, 'Cisatracurium Besylate', to_date('26/01/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (80, 'Bactrim DS', to_date('05/09/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (81, 'Traumeel Combo Pack', to_date('25/01/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (82, 'Aplicare Povidone Iodine', to_date('10/04/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (83, 'Glyset', to_date('11/09/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (84, 'MEDROX', to_date('05/02/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (85, 'SHISEIDO SHEER AND PERFECT FOUNDATION', to_date('09/03/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (86, 'Fluoxetine', to_date('01/06/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (87, 'Hydralazine Hydrochloride', to_date('28/11/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (88, 'Kiehls Since 1851 Dermatologist Solutions Super Fluid UV Defense', to_date('26/10/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (89, 'Clobetasol Propionate', to_date('21/04/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (90, 'BuPROPion Hydrochloride', to_date('11/03/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (91, 'head congestion', to_date('28/08/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (92, 'MISSHA SIGNATURE COMPLEXION COORDINATING BB', to_date('10/01/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (93, 'equaline lice killing', to_date('03/03/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (94, 'Antispetic', to_date('16/02/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (95, 'Assured Day time Cold and Cough', to_date('28/12/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (96, 'Prednisone', to_date('24/12/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (97, 'Calcium carbonate', to_date('03/06/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (98, 'SKYLAKE ORIENTAL HERB EYE', to_date('01/12/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (99, 'AllergyEase Southwestern', to_date('02/12/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (100, 'Amazonian Clay BB Tinted Moisturizer Broad Spectrum SPF 20 Sunscreen', to_date('06/11/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (101, 'Dextroamphetamine Saccharate, Amphetamine Aspartate Monohydrate, Dextroamphetamine Sulfate and Amphetamine Sulfate', to_date('18/08/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (102, 'KE-53PS Gel Hand Sanitizer', to_date('24/02/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (103, 'Sterile Water', to_date('12/11/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (104, 'Roxicet', to_date('04/02/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (105, 'Lidocaine', to_date('28/05/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (106, 'Probenecid', to_date('05/12/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (107, 'Good Neighbor Pharmacy Childrens Pain and Fever', to_date('25/06/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (108, 'Terazosin Hydrochloride', to_date('11/02/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (109, 'Naproxen Sodium', to_date('04/01/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (110, 'Red Mulberry', to_date('28/06/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (111, 'Famotidine', to_date('29/09/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (112, 'care one pain relief pm', to_date('15/05/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (113, 'Burrobrush', to_date('13/02/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (114, 'Fleet', to_date('20/05/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (115, 'AfterBite with Antihistimine', to_date('15/07/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (116, 'Naloxone Hydrochloride', to_date('23/09/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (117, 'Oxycodone Hydrochloride', to_date('05/10/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (118, 'Theophylline Extended Release', to_date('12/06/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (119, 'Moisturizer SPF15', to_date('24/02/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (120, 'Cantharis 30c', to_date('19/02/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (121, 'Sleep Aid', to_date('22/09/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (122, 'Gold Bond Pain Relieving Foot Roll On', to_date('14/09/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (123, 'Ampicillin and Sulbactam', to_date('01/09/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (124, 'Alimta', to_date('30/09/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (125, 'LEADER HYDROCORTISONE WITH ALOE', to_date('17/03/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (126, 'RITUALS broad spectrum SPF 15 sunscreen matt finish foundation SHADE 11', to_date('09/05/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (127, 'Sirolimus', to_date('05/06/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (128, 'PLANTAGO LANCEOLATA POLLEN', to_date('02/01/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (129, 'Sunmark eye itch relief', to_date('20/02/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (130, 'Peptic Relief', to_date('25/06/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (131, 'Derma Blemish Balm', to_date('07/04/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (132, 'Indomethacin', to_date('27/11/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (133, 'No7 Stay Perfect Foundation Sunscreen SPF 15 Buff', to_date('28/03/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (134, 'Potassium Citrate Citric Acid Crystals', to_date('14/06/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (135, 'Mickey Sun Smacker SPF 24 Classic Vanilla', to_date('21/02/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (136, 'Potassium Chloride', to_date('20/07/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (137, 'Colgate', to_date('03/06/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (138, 'Primidone', to_date('21/01/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (139, 'CLE DE PEAU BEAUTE CR COMPACT FOUNDATION', to_date('03/04/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (140, 'ATORVASTATIN CALCIUM', to_date('11/10/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (141, 'Tizanidine', to_date('16/11/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (142, 'Rugby Anti-Dandruff', to_date('07/03/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (143, 'allergy relief d', to_date('26/10/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (144, 'Treatment Set TS348283', to_date('30/11/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (145, 'Niravam', to_date('04/06/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (146, 'Dove', to_date('18/08/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (147, 'DiorSkin Nude 050 Cafe Moka', to_date('06/08/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (148, 'Atovaquone and Proguanil Hydrochloride', to_date('26/07/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (149, 'Cepacol Sensations', to_date('25/11/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (150, 'Estradiol Valerate', to_date('26/08/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (151, 'ChapStick Classic Spearmint', to_date('01/04/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (152, 'Pindolol', to_date('02/06/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (153, 'Epoch', to_date('30/10/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (154, 'Aurax Otic', to_date('06/07/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (155, 'Flu Relief Therapy Day Time', to_date('27/04/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (156, 'Torsemide', to_date('28/09/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (157, 'Stop Smoking Aid', to_date('19/11/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (158, 'sunmark arthricream rub', to_date('13/04/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (159, 'Allergy Relief', to_date('13/11/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (160, 'Grapefruit', to_date('26/05/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (161, 'Omeprazole', to_date('19/10/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (162, 'Quetiapine Fumarate', to_date('29/09/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (163, 'Desert Beige', to_date('04/01/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (164, 'Ambien CR', to_date('20/12/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (165, 'ORCHID BY H E B', to_date('10/02/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (166, 'Paclitaxel', to_date('24/05/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (167, 'Neutrogena MoistureShine SPF20', to_date('20/01/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (168, 'biclora', to_date('25/10/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (169, 'PAROXETINE', to_date('15/06/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (170, 'Pain Relief Aspirin', to_date('27/10/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (171, 'Arnica Rosa', to_date('28/07/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (172, 'Tension Headache Relief', to_date('09/01/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (173, 'Carvedilol', to_date('29/02/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (174, 'Back', to_date('19/01/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (175, 'GENOTROPIN', to_date('17/11/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (176, 'AVINZA', to_date('27/01/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (177, 'ALCOHOL PREP PAD - MEDIUM', to_date('23/07/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (178, 'Amnesteem', to_date('26/06/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (179, 'Rizatriptan Benzoate', to_date('05/02/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (180, 'Zyprexa', to_date('09/03/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (181, 'Chloroquine Phosphate', to_date('05/05/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (182, 'Bactestat', to_date('03/03/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (183, 'Cortomycin', to_date('11/08/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (184, 'Zicam', to_date('03/12/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (185, 'Benadryl Allergy Liqui-Gels', to_date('05/08/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (186, 'Mirtazapine', to_date('19/03/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (187, 'Clomiphene Citrate', to_date('24/06/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (188, 'Cotz Face (For Lighter Skin Tones) SPF 40', to_date('02/11/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (189, 'TOBI', to_date('17/07/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (190, 'Ketorolac Tromethamine', to_date('25/10/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (191, 'Diaper Rash', to_date('26/11/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (192, 'Sertraline Hydrochloride', to_date('13/05/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (193, 'Pure Tan Skin Defense Makeup SPF 15', to_date('09/03/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (194, 'ARTREX', to_date('23/09/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (195, 'Tussin Original', to_date('12/09/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (196, 'SHISEIDO SHEER MATIFYING COMPACT (REFILL)', to_date('17/11/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (197, 'Foam San Hand Sanitizer', to_date('12/11/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (198, 'Ella', to_date('17/08/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (199, 'RECOMBINATE', to_date('02/09/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (200, 'Antiseptic Skin Cleanser', to_date('26/03/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (201, 'Citrus Burst Antibacterial Foaming Hand Wash', to_date('04/11/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (202, 'Trihexyphenidyl Hydrochloride', to_date('03/11/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (203, 'AVAPRO', to_date('25/12/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (204, 'equate hemorrhoidal', to_date('14/01/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (205, 'Ortho Novum', to_date('28/02/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (206, 'FML FORTE', to_date('17/07/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (207, 'wal zyr', to_date('26/05/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (208, 'EXAPRIN', to_date('16/01/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (209, 'Longleaf Pine', to_date('17/08/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (210, 'Prednisone', to_date('12/08/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (211, 'Extra Strength Pain Reliever', to_date('13/04/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (212, 'Mucus ER', to_date('07/01/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (213, 'Balsam Poplar', to_date('30/12/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (214, 'Cefuroxime Axetil', to_date('27/11/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (215, 'Quinapril Hydrochloride and Hydrochlorothiazide', to_date('29/11/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (216, 'Neutrogena', to_date('25/05/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (217, 'FERRUM PHOSPHATE', to_date('28/05/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (218, 'Androgel', to_date('04/01/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (219, 'White Alder', to_date('19/10/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (220, 'La Roche Posay Laboratoire Dermatologique', to_date('29/10/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (221, 'Oxcarbazepine', to_date('13/01/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (222, 'Miconazole 3 Combination Pack', to_date('10/01/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (223, 'Ecotrin', to_date('29/06/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (224, 'NoDoz', to_date('22/01/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (225, 'Bisacodyl', to_date('22/03/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (226, 'Theophylline', to_date('08/09/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (227, 'Mini Berry Lip Balm Blueberry', to_date('18/11/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (228, 'Walgreens Sunscreen', to_date('28/08/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (229, 'COMFORT', to_date('09/10/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (230, 'Venlafaxine Hydrochloride', to_date('27/09/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (231, 'Nystatin', to_date('21/12/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (232, 'Cardiolite', to_date('15/07/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (233, 'Acetylcysteine', to_date('12/10/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (234, 'Illusion Tinted Moisturizer Broad Spectrum Nude', to_date('15/11/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (235, 'Aveeno Baby Soothing Relief Diaper Rash', to_date('16/12/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (236, 'DUREZOL', to_date('15/02/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (237, 'BEEVENOM MASK SHEET', to_date('09/08/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (238, 'ondansetron hydrochloride', to_date('26/10/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (239, 'Best Choice Daytime Severe Cold and Cough', to_date('19/06/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (240, 'Cefoxitin', to_date('09/06/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (241, 'Metformin Hydrochloride', to_date('22/02/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (242, 'Original Extra Strong All Natural Fishermans Friend Menthol Cough Suppressant', to_date('16/02/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (243, 'Kalbitor', to_date('10/11/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (244, 'Upper Respiratory Staph Strep Combination', to_date('28/03/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (245, 'aluminum hydroxide, magnesium hydroxide, simethicone', to_date('23/04/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (246, 'EradiKate Facial Mask', to_date('20/03/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (247, 'Lungs and Bronchial Relief', to_date('20/03/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (248, 'Treatment Set TS128811', to_date('09/03/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (249, 'Naproxen Sodium', to_date('03/01/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (250, 'DayTime Nighttime multi symptom cold and flu relief', to_date('15/07/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (251, 'Mark 3', to_date('10/12/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (252, 'Nivea A Kiss of Vitamin Swirl Antioxidant Enriched Lip Care', to_date('31/08/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (253, 'Bisoprolol Fumarate and Hydrochlorothiazide', to_date('20/06/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (254, 'ENALAPRIL MALEATE AND HYDROCHLOROTHIAZIDE', to_date('14/06/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (255, 'Fluconazole', to_date('14/08/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (256, 'Potassium Chloride in Dextrose', to_date('23/05/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (257, 'Idarubicin Hydrochloride', to_date('15/09/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (258, 'Savella', to_date('20/02/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (259, 'AMOXICILLIN', to_date('07/05/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (260, 'Apis Levisticum Ear Irritation Relief', to_date('27/03/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (261, 'aspirin', to_date('28/01/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (262, 'Nifedipine', to_date('21/09/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (263, 'Perfecting Mineral Beauty Balm with SPF 9', to_date('08/05/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (264, 'Sodium fluoride', to_date('29/12/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (265, 'Oxygen', to_date('24/11/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (266, 'Pollens - Trees, Pecan Carya Carya illinoensis', to_date('02/11/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (267, 'SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)', to_date('08/04/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (268, 'Hongo Killer', to_date('08/02/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (269, 'Terbinafine Hydrochloride', to_date('16/09/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (270, 'Lisinopril', to_date('07/03/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (271, 'CAUSTICUM', to_date('02/09/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (272, 'Propoxyphene and Acetaminophen', to_date('13/01/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (273, 'Xyzal', to_date('09/08/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (274, 'Stool Softener plus Stimulant Laxative', to_date('28/08/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (275, 'RISPERDAL', to_date('12/04/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (276, 'Ban', to_date('24/09/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (277, 'Thiothixene', to_date('22/06/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (278, 'Dr. Cocoa Nighttime Cough and Cold', to_date('30/04/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (279, 'Marcaine with Epinephrine', to_date('06/12/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (280, 'Nevi (Mole) Control', to_date('09/05/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (281, 'Exuviance Multi Protective Day', to_date('24/08/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (282, 'Povidone Iodine Scrub', to_date('22/01/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (283, 'Hydrocodone Bitartrate And Acetaminophen', to_date('14/03/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (284, 'Pleo Form', to_date('21/03/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (285, 'Cefazolin', to_date('17/03/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (286, 'AQUAFRESH', to_date('05/03/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (287, 'Hydrocodone Bitartrate and Acetaminophen', to_date('04/06/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (288, 'Neomycin and Polymyxin B Sulfates', to_date('07/05/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (289, 'Acid Free-Flux', to_date('13/01/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (290, 'Lymph Rx', to_date('20/01/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (291, 'Sysco', to_date('05/03/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (292, 'SULFAMETHOXAZOLE AND TRIMETHOPRIM', to_date('20/11/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (293, 'Etodolac', to_date('14/03/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (294, 'Atenolol', to_date('21/10/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (295, 'Pedia-Lax', to_date('14/05/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (296, 'BETAMETHASONE VALERATE', to_date('20/03/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (297, 'Amlodipine Besylate', to_date('20/01/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (298, 'Efudex', to_date('11/12/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (299, 'Type 11 Dizziness Regular', to_date('17/10/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (300, 'good neighbor pharmacy pain relief', to_date('30/04/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (301, 'Ibuprofen (NSAID) Pain Reliever/Fever Reducer', to_date('13/10/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (302, 'Delsym', to_date('06/03/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (303, 'XtraCare Hand Sanitizer', to_date('11/10/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (304, 'PROBLEND Antibacterial Foam', to_date('22/10/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (305, 'CARBIDOPA AND LEVODOPA', to_date('10/02/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (306, 'Diabetic Siltussin DM DAS-Na', to_date('26/04/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (307, 'Anti-Itch', to_date('24/08/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (308, 'Cell to Cell Essence 70mL', to_date('18/06/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (309, 'Childrens Mucinex', to_date('28/08/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (310, 'Sotalol Hydrochloride', to_date('12/09/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (311, 'PREMIER VALUE ADVANCED EYE DROPS', to_date('19/10/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (312, 'Jhirmack Distinctions Silver Plus Dandruff', to_date('06/02/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (313, 'Phendimetrazine Tartrate', to_date('19/06/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (314, 'Gentamicin Sulfate', to_date('22/02/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (315, 'Rugby Aspirin', to_date('10/04/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (316, 'Anti-Itch', to_date('05/11/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (317, 'Cimetidine', to_date('04/09/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (318, 'PANCREAZE', to_date('22/07/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (319, 'Viscum Mali 4', to_date('18/01/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (320, 'Nateglinide', to_date('28/12/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (321, 'Furosemide', to_date('13/08/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (322, 'Spartan Antiseptic Hand Cleaner', to_date('20/04/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (323, 'Hydroxyzine Hydrochloride', to_date('08/06/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (324, 'Green Pea', to_date('12/07/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (325, 'Metoprolol Tartrate', to_date('09/08/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (326, 'Hydrocortisone', to_date('18/03/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (327, 'ziprasidone hydrochloride', to_date('12/11/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (328, 'BANANA BOAT', to_date('22/12/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (329, 'VERELAN', to_date('24/03/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (330, 'LAURA GELLER BEAUTY TUSCAN SUN SPACKLE SPF 30 PROTECTIVE UNDER MAKE-UP PRIMER PORCELAIN', to_date('15/12/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (331, 'Lotrel', to_date('16/07/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (332, 'Rheumatism', to_date('25/11/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (333, 'NICOTINE', to_date('29/11/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (334, 'Carvedilol', to_date('03/06/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (335, 'Edometriosis', to_date('15/07/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (336, 'Ibuprofen', to_date('27/03/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (337, 'Geotrichum candidum', to_date('08/10/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (338, 'Epsom Salt', to_date('28/08/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (339, 'Dallergy DROPS', to_date('03/12/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (340, 'Prevacid SoluTab', to_date('31/05/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (341, 'Degree', to_date('14/08/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (342, 'Apis Belladonna Mercurius', to_date('25/06/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (343, 'Ipratropium Bromide', to_date('18/11/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (344, 'Genuine First Aid - Home First Aid', to_date('05/05/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (345, 'Ibuprofen PM', to_date('30/11/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (346, 'Sciatic Rescue', to_date('17/02/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (347, 'ADENOSINE', to_date('28/03/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (348, 'Biaxin', to_date('11/04/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (349, 'Carvedilol', to_date('13/02/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (350, 'fondaparinux sodium', to_date('16/12/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (351, 'Tramadol Hydrochloride', to_date('25/09/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (352, 'Acetaminophen', to_date('27/07/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (353, 'Oxygen-Nitrogen Mixture', to_date('08/09/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (354, 'LBEL EFFET PARFAIT MINERAL NATURAL SKIN EFFECT MOUSSE FOUNDATION SPF 16', to_date('04/01/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (355, 'Dextroamphetamine Saccharate, Amphetamine Aspartate Monohydrate, Dextroamphetamine Sulfate and Amphetamine Sulfate', to_date('30/05/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (356, 'equaline pain relief', to_date('01/06/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (357, 'Day Time', to_date('10/08/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (358, 'FEIBA', to_date('31/12/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (359, 'Klor-Con', to_date('13/01/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (360, 'Docu', to_date('19/07/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (361, 'Benzonatate', to_date('22/07/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (362, 'HallsMelon Splash', to_date('03/07/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (363, 'ESIRIN X', to_date('15/10/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (364, 'POLYETHYLENE GLYCOL 3350, SODIUM CHLORIDE, SODIUM BICARBONATE and POTASSIUM CHLORIDE', to_date('25/06/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (365, 'Maximum Strength Flu BP', to_date('19/12/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (366, 'Antibacterial Foaming Hand Sanitizer', to_date('28/11/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (367, 'DEMEROL', to_date('12/09/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (368, 'Diclofenac Sodium', to_date('09/03/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (369, 'Motion Sickness', to_date('17/02/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (370, 'Prochlorperazine Maleate', to_date('23/06/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (371, 'Triazolam', to_date('01/03/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (372, 'House Dust', to_date('11/12/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (373, 'Sal-Plant Gel', to_date('28/03/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (374, 'Degree', to_date('17/03/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (375, 'Temazepam', to_date('11/12/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (376, 'Treatment Set TS350533', to_date('21/12/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (377, 'IVA ANNUA VAR ANNUA POLLEN', to_date('03/09/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (378, 'DILAUDID', to_date('09/07/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (379, 'Glytone Acne Facial Masque', to_date('11/04/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (380, 'ROCK SAUCE', to_date('30/01/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (381, 'ChemoClenz', to_date('06/06/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (382, 'Kids Allergy Eye Relief', to_date('16/05/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (383, 'FENTANYL', to_date('08/03/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (384, 'Warfarin Sodium', to_date('28/07/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (385, 'CALENDULA OFFICINALIS', to_date('10/02/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (386, 'Sofskin Baby', to_date('15/12/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (387, 'Acne Skin eruptions', to_date('25/03/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (388, 'Allergy Relief', to_date('25/04/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (389, 'Atenolol', to_date('16/09/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (390, 'Abridge Cold Sore Treatment', to_date('06/12/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (391, 'Infants Gas Relief', to_date('17/02/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (392, 'amoxicillin and clavulanate potassium', to_date('14/08/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (393, 'SALONPAS PAIN RELIEVING', to_date('24/08/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (394, 'Kadian', to_date('25/07/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (395, 'Syzygium Compositum', to_date('07/06/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (396, 'Premarin', to_date('02/03/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (397, 'Antispetic', to_date('27/02/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (398, 'Arnica', to_date('07/07/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (399, 'Paclitaxel', to_date('05/01/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (400, 'Kentucky Bluegrass (June), Standardized', to_date('30/05/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (401, 'Cepacol', to_date('19/07/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (402, 'Stibium 20 Special Order', to_date('14/08/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (403, 'cephalexin', to_date('11/01/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (404, 'Antacid Antigas', to_date('21/09/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (405, 'Balsalazide Disodium', to_date('04/10/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (406, 'clearlax', to_date('20/02/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (407, 'Furosemide', to_date('21/08/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (408, 'Preferred Plus Maximum Strength Urinary Pain Relief', to_date('10/07/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (409, 'Gabapentin', to_date('01/05/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (410, 'Pollens - Weeds and Garden Plants, Scotch Broom Cytisus scoparius', to_date('04/07/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (411, 'DIAZEPAM', to_date('26/03/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (412, 'Pure Porcelain Skin Defense Makeup SPF 15', to_date('19/11/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (413, 'Belviq', to_date('05/05/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (414, 'Hydralazine Hydrochloride', to_date('16/12/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (415, 'Hydromorphone Hydrochloride', to_date('07/07/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (416, 'Galantamine', to_date('06/07/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (417, 'NEXIUM', to_date('26/03/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (418, 'Chewable Aspirin', to_date('01/01/2022','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (419, 'Morphine Sulfate', to_date('06/04/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (420, 'Standardized Bermuda Grass Pollen', to_date('09/09/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (421, 'Foaming Hand Sanitizer', to_date('23/10/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (422, 'YOUTH SURGE', to_date('01/11/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (423, 'Apis Mell.', to_date('11/08/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (424, 'Metronidazole', to_date('16/07/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (425, 'HETLIOZ', to_date('25/01/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (426, 'Oxaprozin', to_date('22/10/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (427, 'Nitrogen', to_date('06/01/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (428, 'SudoGest', to_date('16/07/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (429, 'Coniferyl Alcohol', to_date('17/06/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (430, 'Cetirizine Hydrochloride', to_date('30/10/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (431, 'Enoxaparin sodium', to_date('08/08/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (432, 'Pollens - Trees, Oak Mix', to_date('25/03/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (433, 'Leader Extra Strength Pain Relief', to_date('29/08/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (434, 'Antibiotic Plus Pain Relief', to_date('16/05/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (435, 'Spironolactone', to_date('28/05/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (436, 'Degree', to_date('06/06/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (437, 'Tramadol Hydrchloride', to_date('13/01/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (438, 'Medicell Scalp', to_date('09/06/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (439, 'Metoclopramide', to_date('09/01/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (440, 'Diazepam', to_date('18/12/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (441, 'Cyproheptadine Hydrochloride', to_date('02/10/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (442, 'Antispetic', to_date('19/10/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (443, 'Enoxaparin Sodium', to_date('19/10/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (444, 'Povidone-Iodine Prep Swabsticks', to_date('09/01/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (445, 'Fentanyl', to_date('08/09/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (446, 'Pollens - Weeds and Garden Plants, Scale, Wing (Shad) Atriplex canescens', to_date('14/10/2012','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (447, 'Plavix', to_date('16/02/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (448, 'Miconazole 3', to_date('16/10/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (449, 'Diphenoxylate Hydrochloride and Atropine Sulfate', to_date('04/02/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (450, 'Stress Tension', to_date('29/05/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (451, 'Pleo Rec', to_date('12/07/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (452, 'Hydroxyzine Hydrochloride', to_date('12/03/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (453, 'antacid', to_date('08/07/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (454, 'ProBlen DNA RNA Rejuvenation', to_date('17/08/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (455, 'Terocin', to_date('26/12/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (456, 'HEMMORHOIDS', to_date('02/12/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (457, 'Lymphomyosot X', to_date('03/08/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (458, 'Evista', to_date('22/01/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (459, 'Wart Free', to_date('02/10/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (460, 'Divalproex Sodium', to_date('07/11/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (461, 'ASPERGILLUS FUMIGATUS', to_date('26/03/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (462, 'Afeditab', to_date('02/06/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (463, 'LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25', to_date('18/09/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (464, 'Purminerals 4 in 1 Makeup SPF 15 Dark', to_date('19/08/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (465, 'Homeopathic Stop Smoking Formula', to_date('09/07/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (466, 'Standardized Sweet Vernal Grass Pollen', to_date('02/10/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (467, 'Lice Treatment', to_date('04/04/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (468, 'Risperidone M-TAB', to_date('03/01/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (469, 'CYZONE', to_date('26/02/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (470, 'Double T', to_date('18/04/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (471, 'Anti Diarrheal', to_date('28/02/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (472, 'DOUBLE PERFECTION LUMIERE', to_date('30/10/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (473, 'Kiehls Since 1851 Facial Fuel UV Guard Broad Spectrum SPF 50 Plus Sunscreen WR80', to_date('13/03/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (474, 'EQUALINE', to_date('18/11/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (475, 'SOLAR SENSE CLEAR ZINC SUNSCREEN FACE and BODY BROAD SPECTRUM SPF 50', to_date('01/03/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (476, 'Fluconazole', to_date('12/02/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (477, 'EPIFOAM', to_date('02/01/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (478, 'Effervescent Pain Relief Fast Relief', to_date('25/04/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (479, 'Ursodiol', to_date('14/06/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (480, 'CLARINS Extra-Comfort Broad Spectrum SPF 15 Sunscreen Tint 108', to_date('08/10/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (481, 'healthy mama', to_date('21/11/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (482, 'Triple Complex Digestion Tonic', to_date('11/01/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (483, 'Doxycycline Hyclate', to_date('24/08/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (484, 'Schein Triple Antibiotic', to_date('31/08/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (485, 'CVS Medicated Chest Rub', to_date('26/02/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (486, 'Exuviance CoverBlend Skin Caring Foundation', to_date('05/07/2014','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (487, 'Chaetomium globosum', to_date('17/09/2015','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (488, 'Hydrocortisone Maximum Strength', to_date('02/06/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (489, 'Instant Hand Sanitizer', to_date('23/05/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (490, 'Old Spice Red Zone Sweat Defense', to_date('26/03/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (491, 'EnLyte', to_date('26/12/2018','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (492, 'Etodolac', to_date('27/12/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (493, 'Metronidazole', to_date('18/05/2017','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (494, 'Speed Stick', to_date('03/06/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (495, 'Keralyt', to_date('14/08/2016','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (496, 'SunZone Kids SPF 30 Sunscreen', to_date('26/07/2019','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (497, 'Justice Strawberry Scent ANTI BAC HAND SANITIZER', to_date('28/07/2013','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (498, 'Sucrose', to_date('20/11/2021','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (499, 'Crest Pro-Health', to_date('07/11/2020','dd/mm/yyyy'));
insert into project (ProjectID, ProjectName, deadline) values (500, 'good neighbor pharmacy pain relief', to_date('20/01/2014','dd/mm/yyyy'));
