insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Shangkuli', 'Lien', 1);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jieshou', 'Rowland', 2);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'Cereté', 'Lien', 3);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Tubungan', '1st', 4);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Bato', 'Harper', 5);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Yujia', 'Division', 6);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jinchang', 'Elgar', 7);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Reims', 'Fairview', 8);
insert into LOCATION (Country, City, Address, LocationID) values ('Gambia', 'Sutukung', 'Mandrake', 9);
insert into LOCATION (Country, City, Address, LocationID) values ('Guatemala', 'Pajapita', 'Forster', 10);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Mandangoa', 'Fordem', 11);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Maracaçumé', 'Brown', 12);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'Caldono', '1st', 13);
insert into LOCATION (Country, City, Address, LocationID) values ('Canada', 'Beaumont', 'Lillian', 14);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Storozhnytsya', 'Pond', 15);
insert into LOCATION (Country, City, Address, LocationID) values ('North Korea', 'Chunghwa', 'Meadow Ridge', 16);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Itabira', 'Hintze', 17);
insert into LOCATION (Country, City, Address, LocationID) values ('Afghanistan', 'Chahār Burj', 'David', 18);
insert into LOCATION (Country, City, Address, LocationID) values ('Kenya', 'Migori', '2nd', 19);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Hengdian', 'Myrtle', 20);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Xiaohebian', 'Tennyson', 21);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Bondy', 'Luster', 22);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Sambiyan', 'Mariners Cove', 23);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Sembakung', 'Merrick', 24);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Antipino', 'Ilene', 25);
insert into LOCATION (Country, City, Address, LocationID) values ('Argentina', 'Laborde', '7th', 26);
insert into LOCATION (Country, City, Address, LocationID) values ('Finland', 'Harjavalta', 'Spohn', 27);
insert into LOCATION (Country, City, Address, LocationID) values ('Norway', 'Oslo', 'Pearson', 28);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Forquilhinha', 'Loeprich', 29);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Ol’ginskaya', 'Glacier Hill', 30);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Nanger', 'Hoepker', 31);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Sardoal', 'Thompson', 32);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Trzebnica', 'Hollow Ridge', 33);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Zhangcun', 'Vahlen', 34);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Toledo', 'Anhalt', 35);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Nahura', 'Red Cloud', 36);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Skołyszyn', 'Mockingbird', 37);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Karangsumber', 'Shoshone', 38);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Partizansk', 'Sommers', 39);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Borovskiy', 'Colorado', 40);
insert into LOCATION (Country, City, Address, LocationID) values ('Argentina', 'Presidencia Roque Sáenz Peña', 'Corscot', 41);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Yangzhuang', 'Meadow Ridge', 42);
insert into LOCATION (Country, City, Address, LocationID) values ('Taiwan', 'Douliu', 'Doe Crossing', 43);
insert into LOCATION (Country, City, Address, LocationID) values ('Mexico', 'San Antonio', 'Hanover', 44);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Qiaoxi', 'Gateway', 45);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Kebonkalapa', 'Bonner', 46);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Gaplokan', 'Northport', 47);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Palompon', '6th', 48);
insert into LOCATION (Country, City, Address, LocationID) values ('Pakistan', 'Lodhrān', 'Mifflin', 49);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Qindu', 'Beilfuss', 50);
insert into LOCATION (Country, City, Address, LocationID) values ('Myanmar', 'Bhamo', 'Dayton', 51);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Huochang', 'Banding', 52);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Kamionka', 'Grim', 53);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Chendong', 'Old Shore', 54);
insert into LOCATION (Country, City, Address, LocationID) values ('Cambodia', 'Lumphăt', 'Tony', 55);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Roissy Charles-de-Gaulle', 'Katie', 56);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Zuocun', 'Towne', 57);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Vernon', 'Basil', 58);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Gunem', 'Fuller', 59);
insert into LOCATION (Country, City, Address, LocationID) values ('Bolivia', 'Azurduy', 'Clove', 60);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Lantian', 'Bluestem', 61);
insert into LOCATION (Country, City, Address, LocationID) values ('Jamaica', 'Black River', 'Maple Wood', 62);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Stari Kuty', 'Eagan', 63);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Tayu', 'Ilene', 64);
insert into LOCATION (Country, City, Address, LocationID) values ('South Africa', 'Kutloanong', 'Heath', 65);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Arcena Pequena', 'Bluestem', 66);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Montongtebolak', '7th', 67);
insert into LOCATION (Country, City, Address, LocationID) values ('United Kingdom', 'Craigavon', 'Burrows', 68);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Pasirpengarayan', 'Di Loreto', 69);
insert into LOCATION (Country, City, Address, LocationID) values ('Japan', 'Abiko', 'Oxford', 70);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Pordapor Barat', 'Vera', 71);
insert into LOCATION (Country, City, Address, LocationID) values ('Croatia', 'Marčelji', 'Porter', 72);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Józefów', 'Tennyson', 73);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Zhulebino', 'Veith', 74);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Coruripe', 'Bultman', 75);
insert into LOCATION (Country, City, Address, LocationID) values ('Thailand', 'Klaeng', 'Reinke', 76);
insert into LOCATION (Country, City, Address, LocationID) values ('Cape Verde', 'Vila Nova Sintra', 'Amoth', 77);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Mników', 'Maryland', 78);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Vyshhorod', 'Eagle Crest', 79);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Sanjia', 'Manley', 80);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Barrinha', 'Fulton', 81);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Jaguariaíva', 'Hovde', 82);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Coutances', 'Bartelt', 83);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Cihurip Satu', 'Iowa', 84);
insert into LOCATION (Country, City, Address, LocationID) values ('Czech Republic', 'Kvasiny', 'High Crossing', 85);
insert into LOCATION (Country, City, Address, LocationID) values ('Netherlands', 'Hilversum', 'Ludington', 86);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Bluri', 'Anhalt', 87);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'Chaparral', 'Rusk', 88);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Dongshe', 'Elmside', 89);
insert into LOCATION (Country, City, Address, LocationID) values ('Latvia', 'Madona', 'Oak', 90);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jiulian', 'Michigan', 91);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Kuningan', 'Lillian', 92);
insert into LOCATION (Country, City, Address, LocationID) values ('United States', 'Miami', 'Spaight', 93);
insert into LOCATION (Country, City, Address, LocationID) values ('United States', 'Norfolk', 'Bellgrove', 94);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jingzhou', 'Loeprich', 95);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Timbrangan', 'Ridge Oak', 96);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Shatoja', 'Northfield', 97);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Capandanan', 'Waubesa', 98);
insert into LOCATION (Country, City, Address, LocationID) values ('Czech Republic', 'Hodkovice nad Mohelkou', 'American Ash', 99);
insert into LOCATION (Country, City, Address, LocationID) values ('Norway', 'Haugesund', 'Sheridan', 100);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Kauran', 'Oak Valley', 101);
insert into LOCATION (Country, City, Address, LocationID) values ('Bosnia and Herzegovina', 'Maglajani', 'Sage', 102);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Luleå', 'Westend', 103);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Viñac', 'Green Ridge', 104);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Juazeiro do Norte', 'Mitchell', 105);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Shuikou', 'American Ash', 106);
insert into LOCATION (Country, City, Address, LocationID) values ('Aruba', 'Angochi', 'Judy', 107);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Sumber', 'Graceland', 108);
insert into LOCATION (Country, City, Address, LocationID) values ('Greece', 'Oinoússes', 'Melody', 109);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Melun', '7th', 110);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Korczew', 'Sherman', 111);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Cilentung', 'Glendale', 112);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Chengdong', 'Browning', 113);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Concordia', 'Maple', 114);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Heshang', 'Old Shore', 115);
insert into LOCATION (Country, City, Address, LocationID) values ('Cambodia', 'Svay Rieng', 'Gulseth', 116);
insert into LOCATION (Country, City, Address, LocationID) values ('Argentina', 'James Craik', '8th', 117);
insert into LOCATION (Country, City, Address, LocationID) values ('Nigeria', 'Batsari', 'Buell', 118);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Mishan', 'Roth', 119);
insert into LOCATION (Country, City, Address, LocationID) values ('Nicaragua', 'Ciudad Darío', 'Farmco', 120);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Yangjiao', 'Stephen', 121);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Jeponkrajan', 'Union', 122);
insert into LOCATION (Country, City, Address, LocationID) values ('Somalia', 'Jilib', 'Welch', 123);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Shixi', 'Tennyson', 124);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Pulian', 'Southridge', 125);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Niemodlin', 'Lakewood Gardens', 126);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Storozhnytsya', 'Gina', 127);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Muzambinho', 'Graedel', 128);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Wola Rębkowska', 'Lakewood', 129);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Nuyno', 'Scofield', 130);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Bollnäs', 'Hallows', 131);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Stockholm', 'Shopko', 132);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Fakel', 'School', 133);
insert into LOCATION (Country, City, Address, LocationID) values ('Armenia', 'Dalarik', 'Cody', 134);
insert into LOCATION (Country, City, Address, LocationID) values ('Germany', 'Essen', 'Dunning', 135);
insert into LOCATION (Country, City, Address, LocationID) values ('Greece', 'Magoúla', 'Dawn', 136);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Prochowice', '6th', 137);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Mesker-Yurt', 'Melvin', 138);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Medveditskiy', 'Rigney', 139);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Pindushi', 'Heath', 140);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Extrema', 'Cascade', 141);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Toritama', 'Center', 142);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Västerås', 'Bartillon', 143);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Maliang', 'Straubel', 144);
insert into LOCATION (Country, City, Address, LocationID) values ('Nepal', 'Dhankutā', 'Carioca', 145);
insert into LOCATION (Country, City, Address, LocationID) values ('Japan', 'Muroto-misakicho', 'Iowa', 146);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Taihua', 'Harper', 147);
insert into LOCATION (Country, City, Address, LocationID) values ('Botswana', 'Khakhea', 'Lake View', 148);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Abut', 'Morningstar', 149);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Dongkan', 'Mayer', 150);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Lasek', 'Maple Wood', 151);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Baipu', 'Warbler', 152);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Bordeaux', 'Sheridan', 153);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Bansalan', 'Cordelia', 154);
insert into LOCATION (Country, City, Address, LocationID) values ('United States', 'Atlanta', 'Magdeline', 155);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Potou', 'Sommers', 156);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Kup', 'Elmside', 157);
insert into LOCATION (Country, City, Address, LocationID) values ('Norway', 'Oslo', 'Rowland', 158);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Rio Claro', 'Commercial', 159);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Hoit Taria', 'Cordelia', 160);
insert into LOCATION (Country, City, Address, LocationID) values ('Argentina', 'Avellaneda', 'Mallard', 161);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Cibitungmasjid', 'Northridge', 162);
insert into LOCATION (Country, City, Address, LocationID) values ('United Kingdom', 'Birmingham', 'Green', 163);
insert into LOCATION (Country, City, Address, LocationID) values ('Canada', 'Beloeil', 'Shoshone', 164);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Xekar', 'Killdeer', 165);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Napalitan', 'Namekagon', 166);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Nagrumbuan', 'Meadow Vale', 167);
insert into LOCATION (Country, City, Address, LocationID) values ('Egypt', 'Samālūţ', 'Mayer', 168);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Brochów', 'Shelley', 169);
insert into LOCATION (Country, City, Address, LocationID) values ('Netherlands', 'Alphen aan den Rijn', 'Amoth', 170);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Oetutulul', 'Gulseth', 171);
insert into LOCATION (Country, City, Address, LocationID) values ('South Africa', 'Komga', 'Commercial', 172);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Banjar Pedawa', '4th', 173);
insert into LOCATION (Country, City, Address, LocationID) values ('Malta', 'Mqabba', 'Golden Leaf', 174);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jinglou', 'Dahle', 175);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Klevan’', 'Dexter', 176);
insert into LOCATION (Country, City, Address, LocationID) values ('Malaysia', 'Nusajaya', 'Autumn Leaf', 177);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Pocohuanca', 'Southridge', 178);
insert into LOCATION (Country, City, Address, LocationID) values ('Venezuela', 'Capacho Viejo', 'Troy', 179);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Utan', 'Redwing', 180);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Bonsari', 'Marcy', 181);
insert into LOCATION (Country, City, Address, LocationID) values ('Japan', 'Shiraoka', 'Alpine', 182);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Zepita', 'Southridge', 183);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Poniatowa', 'Lyons', 184);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Weizhou', 'Pond', 185);
insert into LOCATION (Country, City, Address, LocationID) values ('Honduras', 'El Suyatal', 'Mallard', 186);
insert into LOCATION (Country, City, Address, LocationID) values ('Serbia', 'Sombor', 'Longview', 187);
insert into LOCATION (Country, City, Address, LocationID) values ('Japan', 'Sabae', 'Talisman', 188);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Samangawah', 'Bartelt', 189);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Kuvshinovo', 'Rowland', 190);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Cibeureum', 'Mcbride', 191);
insert into LOCATION (Country, City, Address, LocationID) values ('Mexico', 'Las Americas', 'Donald', 192);
insert into LOCATION (Country, City, Address, LocationID) values ('Serbia', 'Neuzina', 'Bashford', 193);
insert into LOCATION (Country, City, Address, LocationID) values ('Albania', 'Papër', 'Cody', 194);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Deqing', 'Drewry', 195);
insert into LOCATION (Country, City, Address, LocationID) values ('Madagascar', 'Betafo', 'Eastlawn', 196);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Água Levada', 'Lillian', 197);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Poá', 'Sullivan', 198);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Igreja', 'Lakeland', 199);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Agpangi', 'Heath', 200);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Quince Mil', 'Eastwood', 201);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Cola', 'Riverside', 202);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Mingjing', 'Claremont', 203);
insert into LOCATION (Country, City, Address, LocationID) values ('Japan', 'Ushibuka', 'Corben', 204);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Dazhigu', 'Merchant', 205);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Welibo', 'Calypso', 206);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Tualeu', 'Toban', 207);
insert into LOCATION (Country, City, Address, LocationID) values ('Czech Republic', 'Březová', 'Loeprich', 208);
insert into LOCATION (Country, City, Address, LocationID) values ('Nigeria', 'Tofa', 'Maple Wood', 209);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Skärhamn', 'Graceland', 210);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Huaqiao', 'Bartillon', 211);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'El Retorno', 'Hooker', 212);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Żernica', 'Ridge Oak', 213);
insert into LOCATION (Country, City, Address, LocationID) values ('Croatia', 'Zlatar', 'Dryden', 214);
insert into LOCATION (Country, City, Address, LocationID) values ('Mexico', 'Las Flores', 'Esch', 215);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Truskolasy', 'Hermina', 216);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Biryulëvo Zapadnoye', 'Golden Leaf', 217);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Moncada', 'Mccormick', 218);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'San Isidro', 'Dorton', 219);
insert into LOCATION (Country, City, Address, LocationID) values ('Belgium', 'Péruwelz', 'Hintze', 220);
insert into LOCATION (Country, City, Address, LocationID) values ('Iran', 'Bandar-e Lengeh', 'Merrick', 221);
insert into LOCATION (Country, City, Address, LocationID) values ('Croatia', 'Gorjani', 'Commercial', 222);
insert into LOCATION (Country, City, Address, LocationID) values ('Angola', 'Luena', 'Lakeland', 223);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Lidingö', '1st', 224);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Huiyuan', 'Scoville', 225);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Guruafin', 'Crownhardt', 226);
insert into LOCATION (Country, City, Address, LocationID) values ('Cyprus', 'Kyperoúnta', 'Lunder', 227);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Zhanqian', 'Carioca', 228);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Sieniawa Żarska', 'Sommers', 229);
insert into LOCATION (Country, City, Address, LocationID) values ('Pakistan', 'Kot Sultan', 'Duke', 230);
insert into LOCATION (Country, City, Address, LocationID) values ('Thailand', 'Bang Mun Nak', 'Menomonie', 231);
insert into LOCATION (Country, City, Address, LocationID) values ('Pakistan', 'Zafarwāl', 'Starling', 232);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Teresita', 'Oxford', 233);
insert into LOCATION (Country, City, Address, LocationID) values ('United States', 'Torrance', 'Mandrake', 234);
insert into LOCATION (Country, City, Address, LocationID) values ('Republic of the Congo', 'Sibiti', 'Farwell', 235);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Lennec', 'Division', 236);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'Anolaima', 'Lakewood', 237);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Fenshui', 'Delladonna', 238);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Yanqi', 'Cherokee', 239);
insert into LOCATION (Country, City, Address, LocationID) values ('Qatar', 'Ash Shaḩānīyah', 'Russell', 240);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Shigou', 'Farwell', 241);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Tenggina Daya', 'Aberg', 242);
insert into LOCATION (Country, City, Address, LocationID) values ('Nigeria', 'Suleja', 'Anderson', 243);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Krajan', 'Cascade', 244);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jiantianjie', 'Spenser', 245);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Agarsin', 'New Castle', 246);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Chingas', 'Sunnyside', 247);
insert into LOCATION (Country, City, Address, LocationID) values ('Tanzania', 'Rujewa', 'Buell', 248);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Subic', 'Prairieview', 249);
insert into LOCATION (Country, City, Address, LocationID) values ('Mexico', 'Primero de Mayo', 'Lerdahl', 250);
insert into LOCATION (Country, City, Address, LocationID) values ('Mexico', 'Guadalupe Victoria', 'Pawling', 251);
insert into LOCATION (Country, City, Address, LocationID) values ('Estonia', 'Suure-Jaani', 'Alpine', 252);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Huacho', '8th', 253);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'Bogotá', 'Banding', 254);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Rejoso', 'Oxford', 255);
insert into LOCATION (Country, City, Address, LocationID) values ('New Zealand', 'Tauranga', 'Anniversary', 256);
insert into LOCATION (Country, City, Address, LocationID) values ('Croatia', 'Čačinci', 'Florence', 257);
insert into LOCATION (Country, City, Address, LocationID) values ('Canada', 'Harbour Breton', 'Moland', 258);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Tanggung', 'Fairfield', 259);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Rutul', 'Center', 260);
insert into LOCATION (Country, City, Address, LocationID) values ('United States', 'Indianapolis', 'Derek', 261);
insert into LOCATION (Country, City, Address, LocationID) values ('Vietnam', 'Tô Hạp', 'Loomis', 262);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Chennevières-sur-Marne', 'Oriole', 263);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Nanterre', 'Division', 264);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Paisha', 'Pierstorff', 265);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Shiquanhe', 'Upham', 266);
insert into LOCATION (Country, City, Address, LocationID) values ('Greece', 'Markópoulo', 'Vahlen', 267);
insert into LOCATION (Country, City, Address, LocationID) values ('Ecuador', 'Machala', 'Atwood', 268);
insert into LOCATION (Country, City, Address, LocationID) values ('Mexico', 'La Huerta', 'Alpine', 269);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Apostolove', 'Armistice', 270);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Nilópolis', 'Fairfield', 271);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Itaperuna', 'Golden Leaf', 272);
insert into LOCATION (Country, City, Address, LocationID) values ('Argentina', 'La Viña', 'Thompson', 273);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Maloco', 'Ridgeview', 274);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Wuhao', 'Burning Wood', 275);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Dijon', 'Farwell', 276);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Beiqi', 'Westridge', 277);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Cikalong', 'Dakota', 278);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jiuting', 'Merrick', 279);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Lyuban’', 'Northridge', 280);
insert into LOCATION (Country, City, Address, LocationID) values ('Mongolia', 'Bayan', 'Anderson', 281);
insert into LOCATION (Country, City, Address, LocationID) values ('Argentina', 'Capitán Bermúdez', 'Veith', 282);
insert into LOCATION (Country, City, Address, LocationID) values ('Luxembourg', 'Wincrange', 'Bluestem', 283);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Stepanivka', 'Burrows', 284);
insert into LOCATION (Country, City, Address, LocationID) values ('Japan', 'Inuyama', 'Comanche', 285);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'São Bartolomeu', 'Fremont', 286);
insert into LOCATION (Country, City, Address, LocationID) values ('Japan', 'Shinshiro', 'Nobel', 287);
insert into LOCATION (Country, City, Address, LocationID) values ('Togo', 'Badou', 'Delladonna', 288);
insert into LOCATION (Country, City, Address, LocationID) values ('Ecuador', 'Naranjito', 'Mariners Cove', 289);
insert into LOCATION (Country, City, Address, LocationID) values ('Syria', 'Al Ghizlānīyah', 'Oakridge', 290);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Mayorga', 'Lyons', 291);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Huaranchal', 'Di Loreto', 292);
insert into LOCATION (Country, City, Address, LocationID) values ('Greece', 'Níkiti', 'Hermina', 293);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Blois', 'Emmet', 294);
insert into LOCATION (Country, City, Address, LocationID) values ('South Korea', 'Gapyeong', 'Hovde', 295);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Besançon', 'Arkansas', 296);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'San Luis', 'Huxley', 297);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Baishi', 'Aberg', 298);
insert into LOCATION (Country, City, Address, LocationID) values ('Nicaragua', 'Siuna', 'Stang', 299);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Suwalan', 'Cherokee', 300);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Lamatuka', 'Dixon', 301);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Lyuboml’', 'Farragut', 302);
insert into LOCATION (Country, City, Address, LocationID) values ('Argentina', 'Quimilí', 'Anderson', 303);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Juegang', 'Lake View', 304);
insert into LOCATION (Country, City, Address, LocationID) values ('Syria', 'Şalākhid', 'Daystar', 305);
insert into LOCATION (Country, City, Address, LocationID) values ('Thailand', 'Lom Sak', 'Comanche', 306);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Paucarbamba', '4th', 307);
insert into LOCATION (Country, City, Address, LocationID) values ('Argentina', 'Campo Viera', 'Bunting', 308);
insert into LOCATION (Country, City, Address, LocationID) values ('Canada', 'Mascouche', 'Toban', 309);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Itapevi', 'Sauthoff', 310);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Magnitogorsk', 'Elmside', 311);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Heshui', 'Knutson', 312);
insert into LOCATION (Country, City, Address, LocationID) values ('Canada', 'Beloeil', '5th', 313);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Gukovo', 'Del Sol', 314);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Changning', '3rd', 315);
insert into LOCATION (Country, City, Address, LocationID) values ('Vietnam', 'Cam Ranh', 'Mayfield', 316);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Bol’shoye Selo', 'Declaration', 317);
insert into LOCATION (Country, City, Address, LocationID) values ('Greece', 'Lianovérgi', 'Prairie Rose', 318);
insert into LOCATION (Country, City, Address, LocationID) values ('Dominican Republic', 'Majagual', 'Shopko', 319);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Rabig', 'Hoard', 320);
insert into LOCATION (Country, City, Address, LocationID) values ('Malaysia', 'Kota Kinabalu', 'Ridgeway', 321);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Vostryakovo', 'Alpine', 322);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Damulog', 'Annamark', 323);
insert into LOCATION (Country, City, Address, LocationID) values ('Panama', 'El Espino', 'Starling', 324);
insert into LOCATION (Country, City, Address, LocationID) values ('Bosnia and Herzegovina', 'Brka', 'Everett', 325);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Alcoutim', 'Morrow', 326);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Siayan', 'Pankratz', 327);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Eskilstuna', 'Monument', 328);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Kajisara', 'Harbort', 329);
insert into LOCATION (Country, City, Address, LocationID) values ('Thailand', 'Ko Samui', 'Reinke', 330);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Yongfeng', 'Twin Pines', 331);
insert into LOCATION (Country, City, Address, LocationID) values ('New Zealand', 'Takanini', 'Elmside', 332);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Liuxia', 'Delaware', 333);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Pantaibesar', 'Waubesa', 334);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Berestechko', 'Del Mar', 335);
insert into LOCATION (Country, City, Address, LocationID) values ('Mexico', 'San Isidro', 'Talmadge', 336);
insert into LOCATION (Country, City, Address, LocationID) values ('Italy', 'Laspezia', 'Truax', 337);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Umpak', 'Hauk', 338);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Barreiro do Jaíba', 'Bellgrove', 339);
insert into LOCATION (Country, City, Address, LocationID) values ('Marshall Islands', 'Likiep', 'Melby', 340);
insert into LOCATION (Country, City, Address, LocationID) values ('United States', 'Portland', 'Grim', 341);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Saint-Brieuc', 'Tennessee', 342);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Haysyn', 'Stephen', 343);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Sayán', 'Pepper Wood', 344);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Kuanfeu', 'Claremont', 345);
insert into LOCATION (Country, City, Address, LocationID) values ('Croatia', 'Zagreb - Centar', 'Monument', 346);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Houba', 'Myrtle', 347);
insert into LOCATION (Country, City, Address, LocationID) values ('Croatia', 'Repušnica', 'Troy', 348);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Ladário', 'Thackeray', 349);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jangdam', 'Arrowood', 350);
insert into LOCATION (Country, City, Address, LocationID) values ('South Korea', 'Yangp''yŏng', 'Kim', 351);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Lagny-sur-Marne', 'Northland', 352);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'Milán', 'Waxwing', 353);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Xinfeng', 'Sutteridge', 354);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Bao’an', 'Meadow Vale', 355);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Baozi', 'Cody', 356);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Säffle', 'Golf Course', 357);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Raczki', 'Ridge Oak', 358);
insert into LOCATION (Country, City, Address, LocationID) values ('Kenya', 'Isiolo', 'Scofield', 359);
insert into LOCATION (Country, City, Address, LocationID) values ('Armenia', 'Armash', 'Pleasure', 360);
insert into LOCATION (Country, City, Address, LocationID) values ('Canada', 'Saint John', 'Rowland', 361);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Xia Dawo', 'Messerschmidt', 362);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'Don Matías', 'Forster', 363);
insert into LOCATION (Country, City, Address, LocationID) values ('Uganda', 'Gombe', 'Banding', 364);
insert into LOCATION (Country, City, Address, LocationID) values ('Guatemala', 'Ostuncalco', 'Fordem', 365);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Aras-asan', 'Redwing', 366);
insert into LOCATION (Country, City, Address, LocationID) values ('Togo', 'Bafilo', 'Gulseth', 367);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'San Vicente', 'Cardinal', 368);
insert into LOCATION (Country, City, Address, LocationID) values ('Ivory Coast', 'Adzopé', 'Carey', 369);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Iporá', 'Dwight', 370);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Muaralembu', 'Stephen', 371);
insert into LOCATION (Country, City, Address, LocationID) values ('Greece', 'Palaiochóri', 'Michigan', 372);
insert into LOCATION (Country, City, Address, LocationID) values ('Honduras', 'Arada', 'Logan', 373);
insert into LOCATION (Country, City, Address, LocationID) values ('Argentina', 'San Javier', 'Service', 374);
insert into LOCATION (Country, City, Address, LocationID) values ('Nigeria', 'Illela', 'Oakridge', 375);
insert into LOCATION (Country, City, Address, LocationID) values ('Oman', 'Nizwá', 'Northfield', 376);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Timurjaya', 'Mcguire', 377);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Cherbourg-Octeville', 'Vernon', 378);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Piraju', 'Alpine', 379);
insert into LOCATION (Country, City, Address, LocationID) values ('Ecuador', 'Ibarra', 'Redwing', 380);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Kutapanjang', 'Crescent Oaks', 381);
insert into LOCATION (Country, City, Address, LocationID) values ('United States', 'Newark', 'Londonderry', 382);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Shiye', 'Caliangt', 383);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Tacna', 'Mandrake', 384);
insert into LOCATION (Country, City, Address, LocationID) values ('South Korea', 'Jangheung', 'Hazelcrest', 385);
insert into LOCATION (Country, City, Address, LocationID) values ('Czech Republic', 'Rybí', 'Bluejay', 386);
insert into LOCATION (Country, City, Address, LocationID) values ('Nigeria', 'Mberubu', 'Tennessee', 387);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Lushan', 'Coleman', 388);
insert into LOCATION (Country, City, Address, LocationID) values ('Spain', 'Badajoz', 'Marquette', 389);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Almargem do Bispo', 'Debs', 390);
insert into LOCATION (Country, City, Address, LocationID) values ('Spain', 'Albacete', 'Bartelt', 391);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Licupis', 'Coolidge', 392);
insert into LOCATION (Country, City, Address, LocationID) values ('Guatemala', 'Sacapulas', 'Scoville', 393);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Shijing', 'Butterfield', 394);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Kidangbang', 'Del Mar', 395);
insert into LOCATION (Country, City, Address, LocationID) values ('Mexico', 'Adolfo Lopez Mateos', 'Northview', 396);
insert into LOCATION (Country, City, Address, LocationID) values ('Ireland', 'Old Kilcullen', 'Dennis', 397);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Houping', 'Westerfield', 398);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Zwierzyń', 'Transport', 399);
insert into LOCATION (Country, City, Address, LocationID) values ('Albania', 'Fushëkuqe', '4th', 400);
insert into LOCATION (Country, City, Address, LocationID) values ('United States', 'Houston', 'Jenifer', 401);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Jankowice', 'Scofield', 402);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Mangseng', 'Anzinger', 403);
insert into LOCATION (Country, City, Address, LocationID) values ('Ireland', 'Tullamore', 'Continental', 404);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Tlumach', 'Nancy', 405);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'São Fidélis', 'Merrick', 406);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'São Pedro de Muel', 'Towne', 407);
insert into LOCATION (Country, City, Address, LocationID) values ('Italy', 'Palermo', 'Bowman', 408);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Jatiwangi', 'Mesta', 409);
insert into LOCATION (Country, City, Address, LocationID) values ('Cameroon', 'Edéa', 'Delaware', 410);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Burgos', 'Memorial', 411);
insert into LOCATION (Country, City, Address, LocationID) values ('United States', 'Lansing', 'Carey', 412);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jiulong', 'Dovetail', 413);
insert into LOCATION (Country, City, Address, LocationID) values ('Greece', 'Spárti', 'Union', 414);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Esposende', 'American Ash', 415);
insert into LOCATION (Country, City, Address, LocationID) values ('Japan', 'Ōgaki', 'Old Gate', 416);
insert into LOCATION (Country, City, Address, LocationID) values ('Croatia', 'Buzet', 'Hansons', 417);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Casa Nova', 'Sutherland', 418);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Nis’oni', 'Dennis', 419);
insert into LOCATION (Country, City, Address, LocationID) values ('Germany', 'Dresden', 'Meadow Ridge', 420);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Golcowa', 'Gateway', 421);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Famões', 'Dwight', 422);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Fenkeng', 'Pawling', 423);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Zhaojia', 'Petterle', 424);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'Mitú', 'Sheridan', 425);
insert into LOCATION (Country, City, Address, LocationID) values ('Solomon Islands', 'Gizo', 'Service', 426);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Bodeh', 'Fremont', 427);
insert into LOCATION (Country, City, Address, LocationID) values ('Colombia', 'Rivera', 'Golf Course', 428);
insert into LOCATION (Country, City, Address, LocationID) values ('Netherlands', 'Dongen', 'Londonderry', 429);
insert into LOCATION (Country, City, Address, LocationID) values ('Turkmenistan', 'Mary', 'Hudson', 430);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Verbivka', 'Eliot', 431);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Zhongnan', 'Kedzie', 432);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Maesan', 'Bunker Hill', 433);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Mintian', 'Haas', 434);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Eskilstuna', 'Sauthoff', 435);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Novovorontsovka', 'Express', 436);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Bilyarsk', 'Vera', 437);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Rio', 'Kinsman', 438);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Jianggang', 'Maple Wood', 439);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Sinarjaya', 'Riverside', 440);
insert into LOCATION (Country, City, Address, LocationID) values ('Afghanistan', 'Ārt Khwājah', 'Crowley', 441);
insert into LOCATION (Country, City, Address, LocationID) values ('Poland', 'Ursus', 'Sundown', 442);
insert into LOCATION (Country, City, Address, LocationID) values ('Kenya', 'Kilifi', 'David', 443);
insert into LOCATION (Country, City, Address, LocationID) values ('Vietnam', 'Ngô Đồng', 'Rieder', 444);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Sanghan', 'Hollow Ridge', 445);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Laka', 'Burrows', 446);
insert into LOCATION (Country, City, Address, LocationID) values ('Vietnam', 'Phú Lộc', 'Harper', 447);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Dongpu', 'Anzinger', 448);
insert into LOCATION (Country, City, Address, LocationID) values ('Japan', 'Yaizu', 'Hagan', 449);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Sancha', 'Maple Wood', 450);
insert into LOCATION (Country, City, Address, LocationID) values ('Syria', '‘Uqayribāt', 'East', 451);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Miaoyu', 'Wayridge', 452);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Västerås', 'Bartelt', 453);
insert into LOCATION (Country, City, Address, LocationID) values ('Norway', 'Oslo', 'Lindbergh', 454);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Goubangzi', 'Delladonna', 455);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Mingcheng', 'Pond', 456);
insert into LOCATION (Country, City, Address, LocationID) values ('Peru', 'Mollebamba', 'Oak Valley', 457);
insert into LOCATION (Country, City, Address, LocationID) values ('Afghanistan', 'Fayzabad', 'Briar Crest', 458);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Goryachevodskiy', 'Old Shore', 459);
insert into LOCATION (Country, City, Address, LocationID) values ('Portugal', 'Bairro de Santo António', 'Village Green', 460);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Xiabao', 'Lien', 461);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Keli', 'Clarendon', 462);
insert into LOCATION (Country, City, Address, LocationID) values ('Germany', 'Bochum', 'Stang', 463);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Balungkopi', 'Golden Leaf', 464);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Rajal Norte', 'Starling', 465);
insert into LOCATION (Country, City, Address, LocationID) values ('Micronesia', 'Faraulep', 'Jana', 466);
insert into LOCATION (Country, City, Address, LocationID) values ('Ireland', 'Dublin', 'Brown', 467);
insert into LOCATION (Country, City, Address, LocationID) values ('South Africa', 'Mandeni', 'Utah', 468);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Samagaltay', 'Monica', 469);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Qingliu', 'Evergreen', 470);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Wanxian', 'Karstens', 471);
insert into LOCATION (Country, City, Address, LocationID) values ('Spain', 'Zamora', 'Brown', 472);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Sosnytsya', 'Claremont', 473);
insert into LOCATION (Country, City, Address, LocationID) values ('Brazil', 'Mendes', '8th', 474);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Huaqiao', 'Talisman', 475);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Qiantang', 'Northfield', 476);
insert into LOCATION (Country, City, Address, LocationID) values ('South Africa', 'Tarkastad', 'Eggendart', 477);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Duri', 'Blaine', 478);
insert into LOCATION (Country, City, Address, LocationID) values ('Ukraine', 'Berezivka', 'Graceland', 479);
insert into LOCATION (Country, City, Address, LocationID) values ('Sri Lanka', 'Nuwara Eliya', 'North', 480);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Bianxiong', 'Donald', 481);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Sanhui', 'Oneill', 482);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Cibolang', 'Springview', 483);
insert into LOCATION (Country, City, Address, LocationID) values ('Croatia', 'Krasica', 'Fair Oaks', 484);
insert into LOCATION (Country, City, Address, LocationID) values ('Malaysia', 'Petaling Jaya', 'Johnson', 485);
insert into LOCATION (Country, City, Address, LocationID) values ('Czech Republic', 'Žacléř', 'Northland', 486);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Moscow', 'Carioca', 487);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Gununggoong', 'Dryden', 488);
insert into LOCATION (Country, City, Address, LocationID) values ('France', 'Paris 17', 'Crest Line', 489);
insert into LOCATION (Country, City, Address, LocationID) values ('Chad', 'Faya-Largeau', '6th', 490);
insert into LOCATION (Country, City, Address, LocationID) values ('China', 'Luntai', 'Melvin', 491);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Kiamba', 'Cascade', 492);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Sindangan', 'Swallow', 493);
insert into LOCATION (Country, City, Address, LocationID) values ('Sweden', 'Oxelösund', 'Harbort', 494);
insert into LOCATION (Country, City, Address, LocationID) values ('Russia', 'Tirlyanskiy', 'Stone Corner', 495);
insert into LOCATION (Country, City, Address, LocationID) values ('Philippines', 'Ragay', 'Surrey', 496);
insert into LOCATION (Country, City, Address, LocationID) values ('Thailand', 'Raman', 'Dahle', 497);
insert into LOCATION (Country, City, Address, LocationID) values ('Indonesia', 'Jagabaya Dua', 'Merchant', 498);
insert into LOCATION (Country, City, Address, LocationID) values ('Thailand', 'Kuchinarai', 'Oxford', 499);
insert into LOCATION (Country, City, Address, LocationID) values ('Malawi', 'Mchinji', 'Montana', 500);
